name: Deploy Java War package to Azure web app

on:
  [push,pull_request]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
# env:
#  AZURE_WEBAPP_NAME: tomcatinfo-github-action  # set this to your application's name
#  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }} # set this to the path to your web app project
#  JAVA_VERSION: '11'                # set this to the java version to use
#  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}     # set GH repo secret with the publish profile of the web app

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Build with Maven
      run: mvn package --file pom.xml

    # - name: Azure Login
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'tomcatinfo-github-action'
        publish-profile: ${{ secrets.PUBLISHING_PROFILE }} 
        package: '*.war'
        type: war
        clean: true

    # - name: Azure CLI script file
    #   uses: azure/CLI@v1
    #   with:
    #     # azcliversion: 2.30.0
    #     inlineScript: |
    #       mkdir -p $GITHUB_WORKSPACE/webapps
    #       mv $GITHUB_WORKSPACE/target/tomcatinfo.war $GITHUB_WORKSPACE/webapps
    #       cd $GITHUB_WORKSPACE
    #       zip -0 -r webapps.zip webapps
    #       unzip -v $GITHUB_WORKSPACE/webapps.zip
    #       az webapp deploy --resource-group tomcatinfo-github-action-rg --name tomcatinfo-github-action --type zip --src-path $GITHUB_WORKSPACE/webapps.zip

    # - name: 'Deploy to Azure WebApp'
    #   uses: azure/webapps-deploy@v2
    #  with: 
    #    app-name: ${{ env.AZURE_WEBAPP_NAME }}
    #    publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #    # package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/tomcatinfo.war'
    #    package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/tomcatinfo.zip'
        
  # For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
